sudo: required
services:
  - docker
before_intall:
  - docker build -t ecosyn/docker-multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ecosyn/docker-multi-client-test npm test -- --coverage

after_success:
  - docker build -t ecosyn/docker-multi-client ./client
  - docker builr -t ecosyn/docker-multi-nginx ./nginx
  - docker build -t ecosyn/docker-multi-server ./server
  - docker build -t ecosyn/docker-multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
